### ISSUE TITLE
Intermittent issue when clicking an image in admin

### ISSUE THREAD

**Issue by blongden** [codem/DisplayAnything#15]
Occasionally (but not always) there's a problem when clicking an image to edit its details in the admin back end. When the problem occurs, you don't even see the 'Loading' text and the popup remains white. The close button does not work and the only way out is to refresh the screen.

The problem can usually be bypassed by clicking an image in a different browser in the admin back end to the one that is exhibiting the problem - once it works - it will work in the original browsers too.

**Comment by blongden** [comment]
Playing around with this a bit more... I cannot replicate this with a debugger open (chrome & firebug). If I clear my cache and don't have a debugger open it appears to do it once, when I refresh the screen everything appears to work again. Suggests something to do with the order that javascript is included vs items in the local cache etc. Will comment if I get any further.

**Comment by MrJamesEllis** [comment]
Sounds like a WSOD. Can you put your development site in dev mode with error display on, get a backtrace and copy the important bits here.

**Comment by blongden** [comment]
Fairly certain this is not WSOD. There's no backtrace or error (I am in dev mode). I can reproduce every time if I clear cache, log in to /admin, browse to a gallery and click on an image.

I can however visit the /admin/EditForm/field/SomeGallery/item/1/DetailForm/field/GalleryItems/item/99/edit/?SecurityID=xxx URL and get the content I expect in the overlay. The page then works as expected once I refresh and try again.

**Comment by blongden** [comment]
Seems like this may have been a bug in Silverstripe 2.4.5. Upgrading to 2.4.7 appears to have made the problem go away. I'll reopen this if it reappears!
