### ISSUE TITLE
edit to readme.md

### ISSUE THREAD

**Issue by bbowden** [codem/DisplayAnything#3]
James,
Next time I will have learnt more about github but meanwhile here are a couple of edits for readme.md:

Line 72: change status to static
Line 75: change DisplayAnythingVideoGallery to DisplayAnythingYouTubeGallery
Line 93: change FeatureImage to SomeImage

I'm using the code straight from the read me and I'm now getting the admin page to load but only getting the "Loading uploader..." message so far. I'm travelling for the rest of the week so may not get a chance to sort out my last bugs till next week. If they can be addressed with updates to the documentation, I'll let you know.

Congratulations on this module. Its exactly what I was looking for - no dependancies on other modules and I can implement my own front end without having to hack existing code.

cheers
bruce

**Comment by MrJamesEllis** [comment]
Thanks Bruce, just pushed an update to readme.md

Graphical diff is here:
https://github.com/codem/DisplayAnything/commit/75edc38f3b4f12534745696e6867ee048a8d9e11

**Comment by bbowden** [comment]
James,
Now for the next issue. When I create a gallery page, I get the Gallery, Image and Video tabs OK but the Loading Uploader... message never goes away. Looking at the html shows why:

<div class="uploadanything-upload-box" id="Form_EditForm_SomeGallery" rel="{&quot;action&quot;:&quot;admin\/EditForm\/field\/SomeGallery\/Upload?SecurityID=80e7fa31bb54f997582417e1b94c1a9541f1f83f&quot;,&quot;reload&quot;:&quot;admin\/EditForm\/field\/SomeGallery\/ReloadList?SecurityID=80e7fa31bb54f997582417e1b94c1a9541f1f83f&quot;,&quot;params&quot;:{&quot;record&quot;:{&quot;d&quot;:&quot;GalleryPage&quot;,&quot;p&quot;:{&quot;ID&quot;:37}}}}">Loading uploader...</div>


The GetUploaderConfiguration returns that long string filled with &quot; which, presumably, should trigger the javascript but fails to do so. 

Any suggestions as to where to go next to get it working?

cheers
Bruce Bowden
Frogmouth Communications
40 Blackburn St, Bittern, Vic 3918
ph: 03 5983 0428
mobile: 0402 339 550

http://frogmouth.com.au/

**Comment by MrJamesEllis** [comment]
The rel attribute carries around some JSON encode information about the gallery.

Have you pulled the latest version from Github ? looks like some JS is not being fired. Try clearing your cache and reloading.

Also, what browser is this appearing in?

**Comment by MrJamesEllis** [comment]
see Issue #5
