### ISSUE TITLE
Issues when deleting images

### ISSUE THREAD

**Issue by rs26** [codem/DisplayAnything#4]
When I tried to delete images from a gallery, I am getting:
`event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.`

and:
`Refused to set unsafe header "Connection"`

SilverStripe v2.4.6

**Comment by MrJamesEllis** [comment]
both are unrelated to the module, you'll find the first one appeared with a recent release of Chrome and probably all webkit browsers. something to do with the old version of jquery shipped with Silverstripe (1.4.2 I believe).

the latter one is related to the Silverstripe core.

thanks
James
