### ISSUE TITLE
uploader not loading on new clean install

### ISSUE THREAD

**Issue by bbowden** [codem/DisplayAnything#5]
James,
I have created a new 2.4.6 install of SS and loaded DisplayAnything, using the code in the documentation to create GalleryPage.php and GalleryPage.ss.
The Gallery, Image and Videos tabs load correctly and within the Gallery tab, everything seems to load except that the Loading uploader... message never goes away.

I'm running Safari on Mac OS X using the local Apache/PHP/MySQL webserver. I get the same result in Firefox or loading DisplayAnything onto a VPS hosted site.

I am guessing there is something missing in the documentation that more knowledgable people are automatically fixing.

**Comment by MrJamesEllis** [comment]
That would be Javascript error. What does the Firebug or Chrome/Safari console say (F12) ?

I'll try running up a super clean install and attempt to duplicate it.

**Comment by bbowden** [comment]
James,
Neither the Safari console nor the apache error log are reporting any problems. I had attached my Gallerypage.php, assuming attachments are allowed.

cheers
Bruce Bowden
Frogmouth Communications
40 Blackburn St, Bittern, Vic 3918
ph: 03 5983 0428
mobile: 0402 339 550

http://frogmouth.com.au/

**Comment by MrJamesEllis** [comment]
Bruce, I did a fresh clean install of 2.4.6 and dropped in DA, then ran a /dev/build and the required fields were created.

I then knocked together a GalleryPage and it all worked just fine.

That said, you're obviously having some problems setting this up. Can you confirm you are using the most recent source code. When developing, ensure SS is ing 'dev' mode by using "Director::set_environment_type('dev');" in your site config.

Here's the example page I set up:

``` php
<?php
class GalleryPage extends Page {

    public static $has_one = array(
        'ImageGallery' => 'DisplayAnythingGallery',
    );

    public function PublicImageGallery() {
        $gallery = $this->ImageGallery();
        if($gallery->Visible == 1) {
            return $gallery;
        }
        return FALSE;
    }


    public function getCmsFields() {
        $fields = parent::getCmsFields();

        //GALLERY per page
        $gallery = new DisplayAnythingGalleryField(
            $this,
            'ImageGallery',
            'DisplayAnythingGallery'
        );
        $gallery->SetTargetLocation('gallery_files');
        $fields->addFieldToTab('Root.Content.Gallery', $gallery);

        return $fields;
    }
}


class GalleryPage_Controller extends Page_Controller {}
?>
```

**Comment by jamesbolitho** [comment]
Hi Bruce,

I think I was having a similar issue with this and my problem was that I had named the module folder incorrectly.  User Error!  Your module directory should be 'display_anything'. It worked for me after I changed it to that. 

Cheers,

Jim.

**Comment by bbowden** [comment]
Jim,
That was it. A simple name change and everything started working. 

James,
An extra line in the readme file under the 'Installing' heading would help others like me who don't use Git to manage their sites.

cheers
Bruce Bowden
Frogmouth Communications
40 Blackburn St, Bittern, Vic 3918
ph: 03 5983 0428
mobile: 0402 339 550

http://frogmouth.com.au/

**Comment by MrJamesEllis** [comment]
Bruce, I understand, that same issue has hit me before with modules in SS but instructions for install at https://github.com/codem/DisplayAnything/blob/master/readme.md do note that you have to use the directory name display_anything. They are the same whether you use Git, Bzr or a zip download.

Git or Bzr are recommended as you'll be able to keep up to date with code updates as they are released, so it's a skill worth picking up.

Thanks
James

**Comment by bbowden** [comment]
James,
The only time display_anything is mentioned is at the end of the git and bzr commands. If, like me, you are not familiar with these commands, then you ignore those lines as irrelevant and go straight to the download link. 
An extra line stating that the folder must be called display_anything is the only way people like me could know what to do.

However its now working and I'm onto the more interesting bit - building a nice front end to display my gallery.

cheers
Bruce Bowden
Frogmouth Communications
40 Blackburn St, Bittern, Vic 3918
ph: 03 5983 0428
mobile: 0402 339 550

http://frogmouth.com.au/

**Comment by MrJamesEllis** [comment]
Hmm, I see. I'll make an update in the readme file and it'll appear in the next update.

Thanks for the feedback
James
