### ISSUE TITLE
potential bug fix for delete and drag / drop image not displaying in CMS

### ISSUE THREAD

**Issue by jamesbolitho** [codem/DisplayAnything#6]
Hi, thanks for sharing this great module.  Just testing it out today and I noticed that on the admin side that the delete and drag/drop images weren't displaying.  My test site is in a sub directory so the urls were not correct.

My fix change line 529 and 530 of UploadAnythingField.php to:

line 529: 
`$html .= "<a class=\"deletelink\" href=\"{$deletelink}\">
<img src=\"" . Director::BaseURL() . CMS_DIR . "/images/delete.gif\" alt=\"delete\" />
</a>";`
line 530: 
`$html .= "<img src=\"" . Director::BaseURL() . "/display_anything/images/sort.png\" 
title=\"drag and drop to sort\" alt=\"drag and drop to sort\" />";`

Cheers,

Jim

**Comment by MrJamesEllis** [comment]
Jim, thanks for the notification but please clone the module, make the update and submit a pull request on github.

http://help.github.com/pull-requests/

I can then pull the change in, review, test it then publish the change.

Thanks
James

**Comment by MrJamesEllis** [comment]
ref: Issue #7
